import { schemeVariables, type Variant } from "./scheme.js";

/** Static stylesheet for pages without JavaScript: light by default, dark by system preference or data-theme. */
export function staticThemeCss(seed = "#0061a4", variant: Variant = "tonal"): string {
  const block = (vars: Record<string, string>) =>
    Object.entries(vars)
      .map(([k, v]) => `  ${k}: ${v};`)
      .join("\n");
  const light = schemeVariables(seed, false, variant);
  const dark = schemeVariables(seed, true, variant);
  return [
    `/* @alllexey/ui theme: seed ${seed}, variant ${variant}. Generated by ui-theme. */`,
    `:root {\n${block(light)}\n  color-scheme: light;\n}`,
    `:root[data-theme="dark"] {\n${block(dark)}\n  color-scheme: dark;\n}`,
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${block(dark).replace(/^/gm, "  ")}\n    color-scheme: dark;\n  }\n}`,
    "",
  ].join("\n");
}
