// Generates src/lib/icons/builtin.ts: path data of the Material Symbols Rounded icons the package itself uses.
// Projects add their own with defineIcons(); `node scripts/icons.mjs name ...` prints entries to paste.
import { readFileSync, writeFileSync } from "node:fs";

const builtin = [
  "menu", "close", "check", "arrow_back", "chevron_right", "keyboard_arrow_down", "palette", "format_paint",
  "light_mode", "dark_mode", "brightness_auto", "warning", "error", "info", "help", "check_circle", "lock",
  "refresh", "search", "more_vert", "open_in_new", "content_copy", "wifi_off", "inbox", "logout", "settings",
  "thumb_up", "thumb_down", "attach_file", "videocam", "description",
];
const filled = ["warning", "error", "check_circle", "info", "thumb_up", "thumb_down"];

const pathOf = (name) => {
  const svg = readFileSync(new URL(`../node_modules/@material-symbols/svg-400/rounded/${name}.svg`, import.meta.url), "utf8");
  return svg.match(/ d="([^"]+)"/)[1];
};

const extra = process.argv.slice(2);
if (extra.length) {
  for (const name of extra) console.log(`  ${JSON.stringify(name)}: ${JSON.stringify(pathOf(name))},`);
  process.exit(0);
}
const entries = [...builtin.map((n) => [n, pathOf(n)]), ...filled.map((n) => [`${n}-fill`, pathOf(`${n}-fill`)])];
writeFileSync(
  new URL("../src/lib/icons/builtin.ts", import.meta.url),
  "// Generated by scripts/icons.mjs from @material-symbols/svg-400 (Apache-2.0). Do not edit.\n" +
    "export const builtinIcons: Record<string, string> = {\n" +
    entries.map(([n, d]) => `  ${JSON.stringify(n)}: ${JSON.stringify(d)},`).join("\n") +
    "\n};\n",
);
console.log(`${entries.length} icons`);
